name: basic_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  flutter_plugin_android_lifecycle: ^2.0.28
  horizontal_data_table: ^4.3.1
  intl: ^0.19.0
  fl_chart: ^0.66.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  font_awesome_flutter: ^10.8.0
  cloud_firestore: ^5.6.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_storage: ^12.4.6
  provider: ^6.1.5
  uuid: ^4.3.3
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/personas_data.json
