name: basic_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  flutter_plugin_android_lifecycle: ^2.0.28
  horizontal_data_table: ^4.3.1
  intl: ^0.20.0
  fl_chart: ^0.66.0
  local_auth: ^2.3.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: 2.4.4
  font_awesome_flutter: ^10.8.0
  cloud_firestore: ^5.6.8
  firebase_core: ^3.15.1
  firebase_auth: ^5.5.4
  firebase_storage: ^12.4.6
  provider: ^6.1.5
  uuid: ^4.3.3
  rxdart: ^0.27.7
  qr_flutter: ^4.1.0
  share_plus: ^7.0.2
  path_provider: ^2.0.15
  collection: ^1.18.0
  pdf: ^3.11.3
  open_file: ^3.5.10
  excel: ^2.0.0
  vertical_weight_slider: ^2.6.0
  syncfusion_flutter_sliders: ^30.1.37
  flutter_svg: ^2.2.0
  firebase_messaging: ^15.2.9
  http: ^1.4.0
  printing: ^5.14.2
  flutter_local_notifications: ^19.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
